### ISSUE TITLE
Axis 0 value not displayed

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse/swtchart#353] opened 2023-05-24 19:10 UTC
This is a bug I introduced. https://github.com/eclipse/swtchart/commit/2d0865e339b85c6006a10a22f119b770b263302e

When the value of the y axis is 0, we don't display anything since `double diff = Math.abs((value - tickLabelValues.get(i)) / value);` means `(0.0-0.0)/0.0 < 0.1`

A- Sorry

B- I will try to patch it in the near future.

**Comment by eselmeister** [comment] 2023-05-25 06:49
@MatthewKhouzam Thanks for reporting. I will also have a look at it.

**Comment by iloveeclipse** [comment] 2024-08-29 11:44
Could be a duplicate of https://github.com/eclipse/swtchart/issues/375?

**Comment by eselmeister** [comment] 2024-09-02 04:46
Right, thanks. It's a duplicate of #375.

**Closed as completed by eselmeister** 2024-09-02 04:46 UTC
